### ISSUE TITLE
Bars not disappearing after kill

### ISSUE THREAD

**Issue by Finrodi** [laytya/Chronometer-vanilla#1]
Even though I put "kill" on on (tested with off as well) the bars do not disappear.

**Comment by Nordrassil** [comment]
Same problem.

**Comment by laytya** [comment]
I just checked - its disappear after kill. may be some anather conditions u have?

**Comment by Nordrassil** [comment]
Tried without any addons on both Darrowshire PvE (Elysium) and Kronos 2, mage and warrior. I kill targets, but the debuff bars counting down remain. Kill is checked.

**Comment by Finrodi** [comment]
Yeah, Problem definitely exists.

**Comment by laytya** [comment]
Can you post some screens?

**Comment by Finrodi** [comment]
Im on the way top work right now but there is no error anything. Can post a screenshot of the settings later but they're honestly pretty self-explanatory. Cheers

**Comment by Nordrassil** [comment]
[IMG]http://i66.tinypic.com/2lngi1.png[/IMG]

[IMG]http://i68.tinypic.com/htfhjk.png[/IMG]

**Comment by laytya** [comment]
CoC will never disappear its AoE.
Frost Nova is a same AoE

its timers not only target debuff but timers from applying the AoE.

**Comment by Finrodi** [comment]
Well I am warlock and my dots no not disappear.

**Comment by laytya** [comment]
Im checked it - problem confirmed

**Comment by Finrodi** [comment]
Thanks

**Comment by Nordrassil** [comment]
Yeh sorry, I only took screenshot fo my mage, same problem with warrior and the skill "Rend".
