### ISSUE TITLE
Sheep Countdown randomly disappears

### ISSUE THREAD

**Issue by no-trick-pony** [laytya/Chronometer-vanilla#13]
When I tried Chronometer in Wailing Cavern for the first time I had issues with the time tracking bar randomly disappearing even though the spell (and sheep) was still intact. Version with this issue is the current commit on master ( bcdb57354e4c111f15d5b0e9a25169fddd995815 ).

**Comment by laytya** [comment]
its happens if u kill mob w/ same name... timer diapear if mob u sheeped killed.... so in vanilla i cant track indivisualy each mob... so its not issue of chronometer...
