### ISSUE TITLE
Feed Pet

### ISSUE THREAD

**Issue by Monteo** [laytya/Chronometer-vanilla#14]
Привет, не могу добавить эвент Feed pet Effect в хронометр
![wowscrnshot_071418_140617](https://user-images.githubusercontent.com/24656088/42722056-8da44e76-876f-11e8-889b-f8166aa7b320.jpg)

self:AddTimer(self.SPELL, BS["Feed Pet"],                20, 0,1,0) не помогает

**Comment by Monteo** [comment]
![wowscrnshot_071418_141355](https://user-images.githubusercontent.com/24656088/42722103-6d942326-8770-11e8-8305-e9481c7bc4f4.jpg)
На Бк работает

**Comment by laytya** [comment]
попробуй 
self:AddTimer(self.SPELL, BS["Feed Pet"], 20, 1,0,0)

**Comment by Monteo** [comment]
не работает.

**Comment by laytya** [comment]
Made it work
