### ISSUE TITLE
Не пашет на ханте

### ISSUE THREAD

**Issue by Monteo** [laytya/Chronometer-vanilla#2]
![wowscrnshot_022517_235636](https://cloud.githubusercontent.com/assets/24656088/23333071/b86d129a-fbb7-11e6-8487-896713660140.jpg)
![wowscrnshot_022617_000355](https://cloud.githubusercontent.com/assets/24656088/23333072/b86d6d12-fbb7-11e6-8585-cc9971beb282.jpg)
![wowscrnshot_022617_000532](https://cloud.githubusercontent.com/assets/24656088/23333073/b88d8fde-fbb7-11e6-9efb-c09827f92dc3.jpg)

**Comment by Monteo** [comment]
С библиотекой надо что то сделать

**Comment by Monteo** [comment]
не буду новую тему создавать. Раньше работало 
![wowscrnshot_022617_001408](https://cloud.githubusercontent.com/assets/24656088/23333130/df1cb25a-fbb8-11e6-83a0-7d23d8039ed0.jpg)

**Comment by laytya** [comment]
тебе нада обновить Babble-Spell-2.2 во всех твоих аддонах, на тот что лежит в хронометре. Она самая последняя со всеми правками и руссофицированная. Просто у тяебя какойто другой клиент ее грузит до того как она подгружаетя хронометром.

**Comment by Monteo** [comment]
Спасибо
это был бигвигс
