### ISSUE TITLE
[Sentence] WeakAuras to 2.4.3

### ISSUE THREAD

**Issue by gamer4eg** [laytya/Chronometer-vanilla#21]
I understand that it will be interesting for you to remake someone else's addon, and even in the unpopular version of the game ...
But I dare to hope that you are still interested in this.
For the minimum acceptable work, it is necessary to repair only 3 modules:

Check cooldown skills (you need a dictionary of cd, there is an addon CooldownButtons, you can take from it).

Verification of the possibility of action. (Distance / mute etc.)

Correct check of the amount of resources (mana / hp / rage, etc.)

The author's repo is more likely dead than alive....

https://github.com/obszczymucha/WeakAuras

**Comment by laytya** [comment]
its huge work. i dont have time for it.
