### ISSUE TITLE
How to move the bars?

### ISSUE THREAD

**Issue by FrostShock** [laytya/Chronometer-vanilla#22]
Is there any way to move the bars?

I tried "/chronometer anchor" and it doesn't work. I get the Chronometer menu instead - and I can't find options for the bar positions.

It worked on version 0.10 (ReleaseDate: 2006-10-25), but it doesnt work on last version (1.13)

Also, I have an issue with [Antagonist](https://legacy-wow.com/vanilla-addons/antagonist/), if I'm using Chronometer. It doesn't work and it gives this error:

Error: ...AddOns\Antagonist\libs\CandyBar-2.0\CandyBar-2.0.lua:122: attempt to index field `var' (a nil value)

**Comment by laytya** [comment]
its not working on 1.13+ .only Vanilla
