### ISSUE TITLE
Missing spells

### ISSUE THREAD

**Issue by olepg** [laytya/Chronometer-vanilla#6]
Flurry shaman ability is missing.
http://db.vanillagaming.org/?spell=12319
Orc racial debuff is missing. (Healing reduction penalty for 25sec)
http://db.vanillagaming.org/?spell=23230

**Comment by laytya** [comment]
Flurry not timed, its only have counts. So u can track it by MPOWA or POWA...

About Blood Fury - theris bug or error on Elysium - there is no combat log about it =)

**Comment by kaadai** [comment]
Fire Vulnerability (from Improved Scorch) seems to be missing. 
http://db.vanillagaming.org/?spell=22959
30 sec debuff. I think its refreshed to max duration each time you succesfully hit with Scorch, but not 100% sure. 
Will this be added? Or is it covered by another addon? I havent found any working yet.

**Comment by laytya** [comment]
its not missing, just dont working, i found misstake. see in next update
