### ISSUE TITLE
german client mage lua-error

### ISSUE THREAD

**Issue by Mixuspidelix** [laytya/Chronometer-vanilla#7]
interface\Addons\Chronometer\Data\Mage.lua:15: Babble-Spell-2.2: Translation "Counterspell-Silenced" does not exist.

Can you help me by this? thanks Mixus

**Comment by laytya** [comment]
need translation of 
3102:		["Counterspell - Silenced"] = "Counterspell - Silenced",  --  Need to translated

in german locale of babble-spell lib. there are more not translated spells...

**Comment by Mixuspidelix** [comment]
i would translate *Counterspell - Silenced = Gegenzauber - zum Schweigen gebracht* but when i insert this in the Babble-Spell-2.2.lua, the error is always there :s 

Thanks, Mixus.
