### ISSUE TITLE
New candybar lib version breaks bigwigs bars

### ISSUE THREAD

**Issue by PeTeFIN** [laytya/Chronometer-vanilla#8]
Both addons use the same library, using the 0.12 version breaks bigwigs bar functionality.

Bigwigs is using the 15771.

**Comment by Nordrassil** [comment]
Can confirm same issue, weirdly enough this is only a problem on some characters, paladin works fine for some reason >.<

**Comment by laytya** [comment]
you need update candybar lib in bigwigs, its compatible....
